version: "3.12"

services:
  db:
    container_name: url_shortener_db
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    container_name: url_shortener_app
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "sleep 5 &&
      alembic upgrade head &&
      gunicorn app.main:app --workers 3
      --worker-class uvicorn.workers.UvicornWorker
      --bind=0.0.0.0:8000
      --timeout 120"

volumes:
  postgres_data: