"""Add ClickLog table and relationship

Revision ID: eb19d1eee203
Revises: 166317042c94
Create Date: 2025-06-02 13:24:58.468680

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'eb19d1eee203'
down_revision: Union[str, None] = '166317042c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_click_logs_clicked_at'), 'click_logs', ['clicked_at'], unique=False)
    op.create_index(op.f('ix_click_logs_id'), 'click_logs', ['id'], unique=False)
    op.create_index(op.f('ix_click_logs_url_id'), 'click_logs', ['url_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_click_logs_url_id'), table_name='click_logs')
    op.drop_index(op.f('ix_click_logs_id'), table_name='click_logs')
    op.drop_index(op.f('ix_click_logs_clicked_at'), table_name='click_logs')
    op.drop_table('click_logs')
    # ### end Alembic commands ###
